### ISSUE TITLE
Send gzipped JSONs?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#104]
Working on the R package. Getting synth trees via ```getSyntheticTree``` plugin can take a while. As worked with the similar [Phylografter] (https://github.com/OpenTreeOfLife/phylografter/pull/44) issue, it might behoove us to (optionally) send compressed data. I will look into this.

**Comment by jimallman** [comment]
FYI, I believe this is will be satisfied by the [proposed caching of getSyntheticTree results in web2py](https://github.com/OpenTreeOfLife/opentree/pull/591). Hopefully we can merge and deploy this later in the week.
