### ISSUE TITLE
production machine not returning git_sha

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#123]
this may be an artifact of deployment before a code change.
When I call 

     curl -X POST -H "Content-Type":"application/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/tree_of_life/about

I get back entries like:
    {
    "study_id" : "2849",
    "git_sha" : "",
    "tree_id" : "6615"
}

Note the lack of `pg_` in the study_id and the empty SHA. Calling graph/source_tree then fails (adding the `pg_` or omitting it and with an empty or absent `git_sha` (curl of these 4 combos below)
    
    $ curl -X POST -H "Content-Type":"aplication/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/graph/source_tree --data '{"git_sha": "", "study_id": "2849", "tree_id": "6615"}'
{
  "error" : "Invalid source id provided."
}

   $ curl -X POST -H "Content-Type":"aplication/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/graph/source_tree --data '{"git_sha": "", "study_id": "pg_2849", "tree_id": "6615"}'
{
  "error" : "Invalid source id provided."
}

    $ curl -X POST -H "Content-Type":"aplication/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/graph/source_tree --data '{"study_id": "pg_2849", "tree_id": "6615"}'{
  "message" : "Mandatory argument \"git_sha\" not supplied.",
  "exception" : "IllegalArgumentException",
  "fullname" : "java.lang.IllegalArgumentException",
  "stacktrace" : [ "org.neo4j.server.plugins.ParameterExtractor.extract(ParameterExtractor.java:47)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:53)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
}

    $ curl -X POST -H "Content-Type":"aplication/json" -H "Accept":"application/json" http://api.opentreeoflife.org/v2/graph/source_tree --data '{"study_id": "2849", "tree_id": "6615"}'
{
  "message" : "Mandatory argument \"git_sha\" not supplied.",
  "exception" : "IllegalArgumentException",
  "fullname" : "java.lang.IllegalArgumentException",
  "stacktrace" : [ "org.neo4j.server.plugins.ParameterExtractor.extract(ParameterExtractor.java:47)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:53)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]

**Comment by josephwb** [comment]
This looks fixed.
