### ISSUE TITLE
array out of bounds & empty stack trace for induced_subtree request with 159 ids

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/treemachine#130]
I'm getting an array out-of-bounds error with an empty stack trace.  The json return and the exact command are given below.  This has nothing to do with curl--  I can run the same thing in DHC (chrome extension) and I get the same error.  The command is not poorly formed-- I can cut out the latter half of the ids and it works. This has only 159 ids which is not over the limit. 

{
"exception":"ArrayIndexOutOfBoundsException",
"fullname":"java.lang.ArrayIndexOutOfBoundsException",
"stacktrace":[
]
}

curl -X POST http://devapi.opentreeoflife.org/v2/tree_of_life/induced_subtree -H "Content-Type:application/json" -d '{"ott_ids":[797186,1069768,799880,325577,771681,265527,909424,916001,345202,515700,379288,821359,339361,459708,681762,429474,339369,833632,899964,279981,222794,1020638,388185,8861,374288,630561,2857781,1006246,756728,852873,40959,135756,236255,825707,989229,799391,1065959,259054,181153,339346,842200,991614,5256770,473836,532288,1006256,22343,272926,552986,679535,839027,605194,222781,11561,622458,737614,3904116,317784,3902985,621332,1004808,728680,481682,625750,881533,273185,1075736,1030433,1057986,504628,858818,133143,709884,164191,588060,309234,553005,789008,84004,828461,618115,711300,709900,930715,567481,776348,31926,1082415,494835,5334535,826664,210313,505234,885264,899976,657948,35933,555467,1004806,3904118,1058105,547635,964630,709887,135756,840257,303950,612448,222787,229330,831087,135756,1006251,5516225,1031796,152273,3902937,831084,135756,240937,596473,359073,543978,79347,709892,427869,681762,671802,243145,309263,19798,833644,833629,814207,1081728,183572,709876,426562,1060499,833642,947656,1000262,695389,612429,207474,1065946,709894,407502,413237,806245,5254103,378964,883797,964619,3942433,892369,638936,960334,883511]}'

**Comment by josephwb** [comment]
I am pleased to say this can finally be closed.
