### ISSUE TITLE
For graph/source_tree, can the commit sha be made optional?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#142]
I don't want to have to revise tests every time a study sha changes. I'm OK with changing it if the source tree to be tested stops belonging to the synthetic tree, but not on every change to the study.

Best solution: make it optional, and return the version of the tree that was found in the graph (along with its study's sha). Less good solution: I guess I can get the study list and look up the sha there every time. More work for me.

 graph/source_tree {"study_id":"pg_932", "tree_id":"1831"} 
{
  "message" : "Mandatory argument \"git_sha\" not supplied.",
  "exception" : "IllegalArgumentException",
  "fullname" : "java.lang.IllegalArgumentException",
  "stacktrace" : [ "org.neo4j.server.plugins.ParameterExtractor.extract(ParameterExtractor.java:47)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:53)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
}

**Comment by josephwb** [comment]
Closing this since we are deprecating the service.
