### ISSUE TITLE
clarify mrca web service docs on the issue of MRTA

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#148]
Currently it says the `nearest_taxon...` properties refer to the most recent taxonomic ancestor which is "the closest taxonomic node to the MRCA node in the synthetic tree"

It is really "the closest taxonomic node to the MRCA node in the synthetic tree as one moves towards the root" right? (it will always be the smallest taxon that encompasses the query, not just the "closest" node).

perhaps the current text is fine for a directional distance, but it would not hurt to spell it out.

**Comment by josephwb** [comment]
Fixed with https://github.com/OpenTreeOfLife/treemachine/commit/659d903fad1ce0cdc8d5e966c3ac71c9d3c010ee
