### ISSUE TITLE
clarify the meaning of num_synth_children in the return value of graph_of_life/node_info

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#149]
It seems like it is always equal to the `num_tips` property. I'd expect `num_tips` to be the number of leaves below the node, and `num_synth_children` to be the number of children of the node (which are child nodes in the synthetic tree).

**Comment by josephwb** [comment]
Fixed with https://github.com/OpenTreeOfLife/treemachine/commit/22414b94032f5eaa4229110a42f37734b6009626
