### ISSUE TITLE
non-taxonomic node with out-degree=1

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#151]
I'm not sure how/why this happens, but note that:
   https://tree.opentreeoflife.org/opentree/otol.draft.22@3864282
has only one child and the node is not from a taxonomy.

Can we suppress these?

It causes some weirdness in the UI. @jimallman may want to look at the "Edge to parent null" in the properties panel

**Comment by snacktavish** [comment]
I commented on this problem over here as well: https://github.com/OpenTreeOfLife/treemachine/issues/78

**Comment by mtholder** [comment]
If you grab a version of NCL after today (after https://github.com/mtholder/ncl/commit/596c5a66e9ec9e304711a997f455d8000b8276b1 technically speaking), then you can build a run a tool to check for cases of unnamed nodes with out-degree equal to 1 using;

   make
   ./example/outdeg1count/outdeg1count -frelaxedphyliptree  draftversion2.tre 2>status >output

the `output` that I get is:

    ancestor 1 node(s) before "SubsectionIII ott5246933"
    ancestor 1 node(s) before "Lyngbya ott878838"
    ancestor 1 node(s) before MRCA of "Leptolyngbya sp RS02 ott731044" and"Leptolyngbya sp RS02 ott731044"
    ancestor 1 node(s) before "Arecales ott17706"
    ancestor 1 node(s) before "Typhaceae ott225264"
    ancestor 1 node(s) before "Burasaia ott698917"
    ancestor 7 node(s) before "Barnebyella ott366943"
    ancestor 6 node(s) before "Barnebyella ott366943"
    ancestor 5 node(s) before "Barnebyella ott366943"
    ancestor 4 node(s) before "Barnebyella ott366943"
    ancestor 3 node(s) before "Barnebyella ott366943"
    ancestor 2 node(s) before "Barnebyella ott366943"
    ancestor 1 node(s) before "Barnebyella ott366943"
    ancestor 1 node(s) before "Biserrula ott366947"
    ancestor 1 node(s) before MRCA of "Eutaxia ott405904" and"Isotropis ott382788"
    ancestor 1 node(s) before MRCA of "Macrolobium ott653621" and"Elizabetha coccinea ott656768"
    ancestor 1 node(s) before MRCA of "Asterolinon adoense ott671286" and"Asterolinon adoense ott671286"
    ancestor 1 node(s) before MRCA of "Solanum aviculare ott494825" and"Solanum aviculare ott494825"
    ancestor 1 node(s) before MRCA of "Asclepias aurea ott446754" and"Asclepias aurea ott446754"
    ancestor 1 node(s) before "Eriogonum ott942007"
    ancestor 1 node(s) before "Beta ott892381"
    ancestor 1 node(s) before "Micrabaciidae ott334417"
    ancestor 2 node(s) before "Geotrygon ott449653"
    ancestor 1 node(s) before "Geotrygon ott449653"
    ancestor 4 node(s) before "Columba ott938415"
    ancestor 3 node(s) before "Columba ott938415"
    ancestor 2 node(s) before "Columba ott938415"
    ancestor 1 node(s) before "Columba ott938415"
    ancestor 1 node(s) before MRCA of "Mitu ott488150" and"Nothocrax ott488147"
    ancestor 2 node(s) before MRCA of "Lamprologini ott204877" and"Limnotilapia ott303029"
    ancestor 1 node(s) before MRCA of "Lamprologini ott204877" and"Limnotilapia ott303029"
    ancestor 1 node(s) before "Lamprologini ott204877"
    ancestor 4 node(s) before MRCA of "Simochromis ott710023" and"Limnotilapia ott303029"
    ancestor 3 node(s) before MRCA of "Simochromis ott710023" and"Limnotilapia ott303029"
    ancestor 2 node(s) before MRCA of "Simochromis ott710023" and"Limnotilapia ott303029"
    ancestor 1 node(s) before MRCA of "Simochromis ott710023" and"Limnotilapia ott303029"
    ancestor 1 node(s) before "Pseudosimochromis ott1089695"
    ancestor 1 node(s) before "Istiophoriformes ott5554905"
    ancestor 1 node(s) before "Cirrhitiformes ott930720"
    ancestor 2 node(s) before "Canthigaster ott544462"
    ancestor 1 node(s) before "Canthigaster ott544462"
    ancestor 1 node(s) before "Chelonodon ott95360"
    ancestor 1 node(s) before "Lagocephalus ott986279"
    ancestor 2 node(s) before "Tetraodon ott120280"
    ancestor 1 node(s) before "Tetraodon ott120280"
    ancestor 1 node(s) before "Gerreidae ott132684"
    ancestor 1 node(s) before "Cooperiidae ott939855"
    ancestor 1 node(s) before "Oxyteninae ott586695"
    ancestor 1 node(s) before MRCA of "Munididae ott757798" and"Porcellanidae ott211908"
    ancestor 1 node(s) before "Pachycheles ott1027303"
    ancestor 1 node(s) before "Neopetrolisthes ott474600"
    ancestor 3 node(s) before MRCA of "Lomoidea ott389510" and"Eumunida ott389506"
    ancestor 2 node(s) before MRCA of "Lomoidea ott389510" and"Eumunida ott389506"
    ancestor 1 node(s) before MRCA of "Lomoidea ott389510" and"Eumunida ott389506"
    ancestor 2 node(s) before "Eumunida ott389506"
    ancestor 1 node(s) before "Eumunida ott389506"
    ancestor 2 node(s) before "Pomatochelidae ott190187"
    ancestor 1 node(s) before "Pomatochelidae ott190187"
    ancestor 1 node(s) before "Dorippoidea ott908345"
    ancestor 1 node(s) before MRCA of "Panopeidae ott938012" and"Portunoidea ott757096"
    ancestor 1 node(s) before MRCA of "Dairidae ott531267" and"Carpiliidae ott677778"
    ancestor 1 node(s) before "Dairidae ott531267"
    ancestor 1 node(s) before MRCA of "Cancroidea ott812829" and"Goneplacoidea ott125308"
    78146 named nodes with out degree = 1.
    63 unnamed nodes with out degree = 1.
        14 have parents with names:
            "Leptolyngbya ott757914"
            "commelinids ott225270"
            "Poales ott921871"
            "Detarieae ott792364"
            "Amaranthaceae ott317791"
            "Scleractinia ott712383"
            "Tetraodontidae ott65336"
            "Percomorpharia ott5553753"
            "Trichostrongyloidea ott516800"
            "Saturniidae ott167940"
            "Porcellanidae ott211908"
            "Porcellanidae ott211908"
            "Paguroidea ott131909"
            "Brachyura ott935379"

**Comment by mtholder** [comment]
if you want to jump to the most striking example of this, checkout https://devtree.opentreeoflife.org/opentree/argus/otol.draft.22@3843724
(from the series of ancestors listed above for the taxon "Barnebyella")
