### ISSUE TITLE
Ensure web services work before committing to master

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#152]
api.opentreeoflife.org was working fine when running commit 567e1ee.

Upgraded to b262f55 and the web services stopped working.

Downgraded to 567e1ee and they started working again.

 ../../germinator/test.sh api.opentreeoflife.org
*** Failed: tree_of_life/about {"study_list":false} root_ott_id
{
  "message" : "No such ServerPlugin: \"tree_of_life\"",
  "exception" : "PluginLookupException",
  "fullname" : "org.neo4j.server.plugins.PluginLookupException",
  "stacktrace" : [ "org.neo4j.server.plugins.PluginManager.extension(PluginManager.java:124)", "org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:165)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)", "org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)", "java.lang.reflect.Method.invoke(Method.java:606)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
}

**Comment by jimallman** [comment]
Specifically, the GoLS plugin seems to go missing in the latest version.

**Comment by josephwb** [comment]
How is that possible? I just put up a script unrelated to treemachine code. [GoLS](https://github.com/OpenTreeOfLife/treemachine/tree/master/src/main/java/opentree/plugins) hasn't been touched in 4 months.

**Comment by josephwb** [comment]
Oh, I think this has something to do with GraphExporter.java.

**Comment by jimallman** [comment]
Maybe something from [this recent commit?](https://github.com/OpenTreeOfLife/treemachine/commit/66decab40ea659ce7023ee58a287a4acf6b3c8c8#diff-0)

**Comment by josephwb** [comment]
Actually, I don't believe GraphExporter.java is involved in any way. In fact, none of the changes look relevant. Could this just be a failure to compile?

**Comment by josephwb** [comment]
I can compile and run the plugin locally.

**Comment by josephwb** [comment]
Test:
```bash
curl -X POST http://localhost:7474/db/data/ext/graph/graphdb/about
```
```json
{
  "graph_num_source_trees" : 484,
  "graph_taxonomy_version" : "2.8_5",
  "graph_num_tips" : 2339516,
  "graph_root_name" : "life",
  "graph_root_node_id" : 1,
  "graph_root_ott_id" : 805080
}
```

**Comment by jimallman** [comment]
It's several plugins, actually. Here's what we saw on api.opentreeoflife.org with the latest code:
```bash
curl http://api.opentreeoflife.org/treemachine/ext
```
```bash
{
  "CypherPlugin" : "http://api.opentreeoflife.org:7474/db/data/ext/CypherPlugin",
  "GremlinPlugin" : "http://api.opentreeoflife.org:7474/db/data/ext/GremlinPlugin",
  "GetSASJsons" : "http://api.opentreeoflife.org:7474/db/data/ext/GetSASJsons"
}
```
And again, with the older (working) code:
```bash
curl http://api.opentreeoflife.org/treemachine/ext
```
```bash
{
  "CypherPlugin" : "http://api.opentreeoflife.org:7474/db/data/ext/CypherPlugin",
  "graph" : "http://api.opentreeoflife.org:7474/db/data/ext/graph",
  "GremlinPlugin" : "http://api.opentreeoflife.org:7474/db/data/ext/GremlinPlugin",
  "GetSASJsons" : "http://api.opentreeoflife.org:7474/db/data/ext/GetSASJsons",
  "PhylografterUpdater" : "http://api.opentreeoflife.org:7474/db/data/ext/PhylografterUpdater",
  "GoLS" : "http://api.opentreeoflife.org:7474/db/data/ext/GoLS",
  "tree_of_life" : "http://api.opentreeoflife.org:7474/db/data/ext/tree_of_life"
}```

**Comment by josephwb** [comment]
I've got all of those with the newest code locally. I don't think this is a treemachine issue.

**Comment by josephwb** [comment]
I pushed the new code to devapi, and things work fine:
```bash
curl http://devapi.opentreeoflife.org/treemachine/ext
```
```json
{
  "CypherPlugin" : "http://devapi.opentreeoflife.org:7474/db/data/ext/CypherPlugin",
  "graph" : "http://devapi.opentreeoflife.org:7474/db/data/ext/graph",
  "GremlinPlugin" : "http://devapi.opentreeoflife.org:7474/db/data/ext/GremlinPlugin",
  "GetSASJsons" : "http://devapi.opentreeoflife.org:7474/db/data/ext/GetSASJsons",
  "PhylografterUpdater" : "http://devapi.opentreeoflife.org:7474/db/data/ext/PhylografterUpdater",
  "GoLS" : "http://devapi.opentreeoflife.org:7474/db/data/ext/GoLS",
  "tree_of_life" : "http://devapi.opentreeoflife.org:7474/db/data/ext/tree_of_life"
}
```

**Comment by jimallman** [comment]
OK, I decided to roll the dice and re-deploy all master branches to **api** (production). All plugins now appear and it's working in my testing, as well as the tests here: http://phylo.bio.ku.edu/status/status.html

I'm looking for clues in the neo4j log files, specifically ```ot20:/home/opentree/neo4j-treemachine/data/log/console.log```. This  shows all plugins loading most of the time, but two restarts(?) where only three “core” plugins loaded.

There's no indication as to why, which makes me think either the compiled output for these plugins didn’t make it into place, or some kind of plugin registration didn’t occur normally..?

**Comment by josephwb** [comment]
@jar398 Can we close this?

**Comment by jar398** [comment]
I don't see what else we can do, other than swapping neo4j out for a more
reliable platform, which is probably not practical at this time.

What makes me sweat is that this is one more thing we've got to remember
when deploying: if a plugin is missing, redeploy. Completely unsatisfying.

**Comment by josephwb** [comment]
Not a treemachine issue; seems like maven voodoo. Closing.

**Comment by mtholder** [comment]
seems like this either:
  1. belongs here (if the pom.xml) is not correct.
  2. belongs in a maven issue tracker, if it really is a maven issue (which seems unlikely as none of us seem confident that we know how to use maven), or
  3. in the opentree issue tracker, if the deployment scripts don't do some necessary prep. work.

**Comment by josephwb** [comment]
Can this be recreated? Has it occurred within the last 4 months?

**Comment by jar398** [comment]
Yes, it happened yesterday during production deployment and before that in
development deployment. Each time forcing recompilation and reinstallation
fixed the problem.

But just because it's persistent doesn't mean it can be recreated on demand.

It could be a neo4j bug, or a problem with the deployment system, or one or
more of the pom files. I'm not sure what to do with this one. - At the very
least, when anyone deploys a maven-produced .jar file anywhere, they need
to check that the services work. That would suggest automating this in the
deployment system. I'll put a feature request there, but it checking for
the problem is not the same issue as preventing it from happening in the
first place. I guess I'd like to leave this issue open for a while longer...

**Comment by josephwb** [comment]
Is it just treemachine, or any of the repos that use maven? If the latter, maybe we should move this issue to the main OpenTree repo.

**Comment by jimallman** [comment]
Perhaps we could check for the expected artifacts (compiled plugin files) in the deployment script, and re-run the compilation of any are missing?

**Comment by jar398** [comment]
It happened with oti as well. I'm not sure the opentree repo is the right
place, since this is unrelated to the web app. Maybe germinator, which is
for cross-cutting concerns. Maybe it has something to do with ot-base. I
keep meaning to move the deployment system into its own repo, maybe it
would belong there.

**Comment by jar398** [comment]
No, checking for the artifacts won't work - remember I checked and not only
were they present but they contained the necessary classes. (That argues
against its being a maven problem.) Seems more like a neo4j thing, or a
problem with how the services are being reloaded and restarted.

I think the automatic end-to-end test - making sure the services can be
invoked - is the way to go.
