### ISSUE TITLE
question about edges to licas during TAG creation.

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#161]
no need to respond to this if it makes sense to you. I can look through the code. Just thought I'd post it because I found it surprising.
There is a new test (and I refactored the test harness some to put the output of tests in the testtag dir). That is pushed to https://github.com/OpenTreeOfLife/treemachine/tree/test-refactor

The new test is `ranksforextras` and its tree1 and tree3 are identical to the tree1 and tree2 for the `nontrivialaugmenting` test. I just added a new tree in between them that disagrees about the placement of the "extra" taxa `E` and `F`.  The test passes (it prefers tree2 to tree3), which is great. But I was surprised that in `nontrivialaugmenting` trees 1 and 2 share a lot of nodes:
![nontriv](https://cloud.githubusercontent.com/assets/136067/6042602/83e521d4-ac86-11e4-88ad-b1a9974ea81d.png)

but in `ranksforextras` tree3 is using nodes that are out on their own, and not traversed by tree1  (note tree to color mapping is not consistent):
![ranksforextras](https://cloud.githubusercontent.com/assets/136067/6042884/9a40b98c-ac88-11e4-8967-9be8cef659c3.png)

*updated* tree2 was mislabeled

**Comment by mtholder** [comment]
the second figure from is https://github.com/OpenTreeOfLife/treemachine/tree/test-refactor/test-synth/ranksforextras

**Comment by josephwb** [comment]
tree1: (((A,B),C),D);
tree2: ((A,B),((E,F),C));
tree3: ((((A,E),B),F),C);

**Comment by kcranston** [comment]
When I draw this out, I agree with Mark about n9 == n17, i.e. mrca(tree3,(A,E,B)) and mrca(tree1,(A,B)) should be the same node.

**Comment by blackrim** [comment]
This should be alleviated with deleting the trees and re-adding them. We
know that tree order matters in input and deleting and re inputting is the
way around that. This is default for many of the analyses (discussed by
Cody and Jonathan the other day). The commands for that are java blahblah
pgdelind graphdblocation sourcename
then you add again and should be mapped to both of the lica nodes. Joseph
can perhaps answer more on IRC

**Comment by mtholder** [comment]
calling pgdelind and addnewick to remap seems to help: 

![reprocess](https://cloud.githubusercontent.com/assets/136067/6049154/78f957ca-acb5-11e4-9e74-5463b25198d3.png)

thanks for the help.
