### ISSUE TITLE
incertae sedis erroneouly retained in synthetic tree

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#168]
The current synthetic tree shows OTT taxon 5268476, which is an incertae_sedis container:

https://tree.opentreeoflife.org/opentree/otol.draft.22@384700/Incertae-Sedis

It's a bug that it didn't get squeezed out when OTT 2.8 was generated, but I thought that it would be suppressed by treemachine on load.  Here's the row from OTT:

5268476 |       304358  |       Incertae Sedis  |       no rank |       silva:L37037/#2 |       Incertae Sedis (silva:L37037/#2)        |       incertae_sedis  |

and here's the code from GraphInitializer.java:

			if (tflag.equals("incertae_sedis")){
				System.out.println("skipping incertae_sedis "+name);	
				return;
			}

so I'm baffled as to how this could happen.

**Comment by josephwb** [comment]
Treemachine only uses the flags to determine whether a taxon should be pruned. The version we were using (2.8draft5) has the following:
```
grep "^5268476" Filtered_OTT_taxonomy.tsv
5268476	|	304358	|	Incertae Sedis	|	no rank	|	silva:L37037/#2	|	Incertae Sedis (in domain Eukaryota)	|		|	
```
So, no flag. I don't think treemachine made an error here, so I am closing the issue.

**Comment by jar398** [comment]
OK, I was looking at 2.9, which has it flagged.
This is unfortunate...

**Comment by blackrim** [comment]
Yeah. It is in a pretty good sized list of taxonomy things.

**Comment by josephwb** [comment]
To be clear: no taxa with the "incertae_sedis*" flag is in the tree.
JWB.
