### ISSUE TITLE
Retire return source tree service?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#170]
Described here:

https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#source_tree

Source trees are not stored in the treemachine db anymore (subproblems are). 

In addition, the argument has been made that treemachine should not be providing this info anyway. If the original tree is desired, one should go to phylesystem. If the processed tree is desired, we will provide that in another way.

**Comment by josephwb** [comment]
It has been decided that we will just return a rul to wherever we end up storing the processed newicks.

**Comment by josephwb** [comment]
@kcranston Please send me the link to where these will live as soon as you have it.

**Comment by josephwb** [comment]
@kcranston Apologies if I missed this, but have you set where the processed data are to live? Would like to get this implemented before the PR review / deployment later today (14:00).

**Comment by kcranston** [comment]
Decided to put them on files.opentreeoflife.org

**Comment by josephwb** [comment]
Trees are [here](http://files.opentreeoflife.org/preprocessed/v3.0/).
