### ISSUE TITLE
Update arguson

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#171]
[[Almost done](https://github.com/OpenTreeOfLife/treemachine/commit/7c9195cd0a522851692562d66dbaabb175471ded), but putting this here as a record]

Since moving to subproblem loading, the DB contains less metadata than before, some of which the tree browser expects. @jimallman (on irc) asked for the following to be in the returned arguson:

1. "supportedBy" info for the focal node (present for other nodes, but strangely absent for the focal node). this is an [existing issue](https://github.com/OpenTreeOfLife/opentree/issues/599)
2. metadata for nodes in the "pathToRoot": ottId, taxSource, supportedBy, taxRank, nodeid

That bit is all done, but we need to upgrade to java 8 on dev for testing.

Not unrelated is the [issue](https://github.com/OpenTreeOfLife/opentree/issues/627) regarding the formatting of the "sourceToMetaMap". This will be done shortly.

**Comment by josephwb** [comment]
Should be done with 7e3525c6cf9b6aa4c1e5ad4438c98e03783b579f (see preview in a comment of that commit, since dev is still lacking java 8).

**Comment by jimallman** [comment]
Thanks, this is just what I needed! I'll re-open (or start a new issue) as needed, but closing for now.
