### ISSUE TITLE
possible bug in creating `bipartsByTreeNoDuplicates`

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#172]
shouldn't the addition of `b` to treeBiparts occur after the check to see if `b` has been placed in `bipartId`
here: https://github.com/OpenTreeOfLife/treemachine/blob/rootward-synth/src/main/java/org/opentree/tag/treeimport/BipartOracle.java#L366-L377
?
It looks like `treeNodesForBipart` and `bipartsByTreeNoDuplicates` are getting out of sync.

**Comment by josephwb** [comment]
Closing since this is deprecated.
