### ISSUE TITLE
troubling comment

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#174]
Perhaps the comment is out of date. But as far as I can tell, the flow of execution goes through the part of the code marked with the 

    //TODO: this has an error in it when the clade is not monophyletic

comment, at https://github.com/OpenTreeOfLife/treemachine/blob/rootward-synth/src/main/java/org/opentree/tag/treeimport/BipartOracle.java#L1943

*update*: wrong line linked in the first version of this comment. Link fixed

**Comment by blackrim** [comment]
yes, I agree. I am pretty sure this is just out of date (this commit 8eea261617d03c0c00b805b5c85dea89d66bf0a7 addressed the problem) but I am going to leave it there until it is verified.
