### ISSUE TITLE
Eliminate "Supporting sources for node" messages from console log

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#182]
Supporting sources for node [321058]: [taxonomy]
These messages are useless and are cluttering the log file. Clogged log files make diagnosing server failures harder.

**Comment by jar398** [comment]
These messages are useless and are cluttering the log file. Clogged log files make diagnosing server failures harder.

**Comment by josephwb** [comment]
f1eb8515e2487eeb5c65e0e5c9f2911031ce7f8e should do it. I'll submit a PR sometime soon.
