### ISSUE TITLE
Support OTT 2.9 flags

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#187]
See http://files.opentreeoflife.org/ott/ott2.9/.
unplaced, inconsistent, merged
- treat all same as incertae_sedis

**Comment by josephwb** [comment]
@jar398: The documentation [here](http://files.opentreeoflife.org/ott/ott2.9/) and [here](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/2.9draft8-finishing-up/doc/ott2.9.md) mentions "placed", but not "unplaced". Can I assume that both of those docs have typos, and that the new flag is in fact "unplaced"? That makes a lot more sense when aligning it with "incertae_sedis".

**Comment by jar398** [comment]
Yes.

**Comment by josephwb** [comment]
Looks like"hybrid" was missed (mentioned on the [wiki](https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/Taxon-flags)). Pretty sure we don't want those in the tree.
