### ISSUE TITLE
Some newick downloads failing

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/treemachine#193]
From [opentree issue 758](https://github.com/OpenTreeOfLife/opentree/issues/758):

Some Newick downloads work fine on devtree, some fail. The pattern suggests there might be some kind of "poison pill" (e.g. unexpected punctuation in taxon names), but that's just a hunch.

WORKS: https://devtree.opentreeoflife.org/opentree/argus/ottol@770311/Hominidae

FAILS: https://devtree.opentreeoflife.org/opentree/opentree3.0@3654999/Candidate-division-WS6

**Comment by josephwb** [comment]
Those look like 2 different calls: `...argus/ottol/...` vs. `...opentree3.0...`. Substituting the former in the latter seems to work.

**Comment by josephwb** [comment]
And this involves `arguson`, not `newick`, right?

**Comment by jimallman** [comment]
My bad, the "FAILS" url given here was malformed. See my update and the real "smoking gun" (bad webapp configuration) in https://github.com/OpenTreeOfLife/opentree/issues/758

**Comment by josephwb** [comment]
Great! Thansk for tracking that down @jimallman.
