### ISSUE TITLE
Make synthtree id a passed argument during synthesis

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/treemachine#195]
Currently this value is hardcoded in src/main/java/opentree/constants/GeneralConstants.java.

**Comment by josephwb** [comment]
src/main/java/opentree/constants/GeneralConstants.java is being phased out. Still present at the moment, but not being used.

**Comment by jar398** [comment]
Great.
Do we have a naming convention for these ids? Currently we use opentree4.0
in some places, and draftversion4 in other places. Would be nice to use
same everywhere.

**Comment by josephwb** [comment]
Not as far as I know; they come from the annotations json.
