### ISSUE TITLE
Tree version should be fetched from db in getSourceTree

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#197]
In plugins/graph.java, the tree version number is hardwired into the getSourceTree method.  The id ought to be fetched from the database.

**Comment by jar398** [comment]
Not exactly a dup of #195 since it concerns a different file, but merge the two issues if you like

**Comment by josephwb** [comment]
Not a problem; just need to make sure other tools name things consistently. Synthetic tree names come from the json annotations like:
```
"tree_id": "opentree4.0"
```
Treemachine expects newicks to be present at:
```
http://files.opentreeoflife.org/preprocessed/v4.0/trees/
```

**Comment by jar398** [comment]
As I've said before, we need a document describing the interface between
the synthesis pipeline and tm-lite.  It's OK if tm-lite is capable of
getting its inputs from the web, but this should not be required (i.e. we
want people who don't have the ability and inclination to put things on the
web to be able to run synthesis and tm-lite).​

**Comment by josephwb** [comment]
I guess we can discuss this during the next hangout (or before), but the only interface between the synthesis pipeline and tm-lite is the the generated documents: 1) newick, 2) json annotations.
Regardless, [this](https://github.com/OpenTreeOfLife/treemachine/commit/8873c05fa1bf65e21f148c8d14873a72628a77e2) patches the service as it currently stands.

**Comment by josephwb** [comment]
Not sure why this service was slated for deprecation, but it works (as long as the appropriate files.opentree... directory exists). So this issue (fetch tree version) is satisfied.
