### ISSUE TITLE
Rename 'tree_of_life' plugin class to 'tree_of_life_v3', and remove 'graph'

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#202]
To avoid confusion (false positives, weird errors) in deployment and testing please remove the 'graph' class and rename 'tree_of_life' to 'tree_of_life_v3'.

The 'node_info' method should be part of the 'tree_of_life_v3' class.

Thanks

**Comment by josephwb** [comment]
Done in tm-lite branch.
