### ISSUE TITLE
node_info and mrca methods should gather taxon fields into 'taxon':{...}

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#206]
I think this may be done already for mrca. Needs to be done for node_info as well.

- [ ] [documentation](https://github.com/OpenTreeOfLife/germinator/wiki/Synthetic-tree-API-v3#about_tree)
- [x] test in treemachine/ws-tests
- [ ] implementation in tm-lite branch

    {
      "node_id" : "ott241846",
      “taxon”: {
                 "ott_id" : 241846,
                 "name" : "Neognathae",
                 "rank" : "superorder",
                 "unique_name" : "Neognathae",
                 "tax_sources": ["ncbi:123", "h2007:", "http://dx.doi.org/1234.alskdfj"]
                },
      "synth_id" : "opentree4.1",
    }

**Comment by jar398** [comment]
It looks like this may be the same as mrca with a single node_id, so code can be shared. Having nearest_taxon would definitely be nice.
(But I think we might want to keep this method separate for now.)

**Comment by josephwb** [comment]
So the whole point of `node_info` was to do synthesis queries (support, etc.), not taxonomic queries (that is what taxomachine is for). 
@jar398 _still_ have no clear idea on what you want for node_id. here is my (inevitably incorrect) guess:
```
curl -X POST http://localhost:7474/db/data/ext/tree_of_life_v3/graphdb/node_info -H "content-type:application/json" -d '{"node_id":"ott81461"}'
{
  "synth_data" : {
    "partial_path_of" : {
      "pg_2573_tree5959" : "node1011373"
    },
    "supported_by" : {
      "taxonomy" : "2.9draft12"
    },
    "source_id_map" : {
      "pg_2573_tree5959" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree5959",
        "study_id" : "pg_2573"
      },
      "pg_2822_tree6569" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree6569",
        "study_id" : "pg_2822"
      },
      "taxonomy" : {
        "name" : "ott",
        "version" : "2.9draft12"
      }
    },
    "terminal" : {
      "pg_2822_tree6569" : "ott696271"
    },
    "tip_descendants" : 14302,
    "synth_id" : "opentree4.1"
  },
  "taxon" : {
    "tax_sources" : {
      "irmng" : "1142",
      "worms" : "1836",
      "gbif" : "212",
      "ncbi" : "8782"
    },
    "unique_name" : "Aves",
    "name" : "Aves",
    "rank" : "class",
    "ott_id" : 81461
  },
  "node_id" : "ott81461"
}
```

**Comment by jar398** [comment]
Node_id is the canonical node_id for the node. Usually but not nec. same as
the argument. Correct in your example

-- apologies for brevity / using handheld gizmo --

On Feb 17, 2016, at 0:11, "Joseph W. Brown" <notifications@github.com>
wrote:

So the whole point of node_info was to do synthesis queries (support,
etc.), not taxonomic queries (that is what taxomachine is for).
@jar398 <https://github.com/jar398> *still* have no clear idea on what you
want for node_id. here is my (inevitably incorrect) guess:

curl -X POST http://localhost:7474/db/data/ext/tree_of_life_v3/graphdb/node_info
-H "content-type:application/json" -d '{"node_id":"ott81461"}'
{
  "synth_data" : {
    "partial_path_of" : {
      "pg_2573_tree5959" : "node1011373"
    },
    "supported_by" : {
      "taxonomy" : "2.9draft12"
    },
    "source_id_map" : {
      "pg_2573_tree5959" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree5959",
        "study_id" : "pg_2573"
      },
      "pg_2822_tree6569" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree6569",
        "study_id" : "pg_2822"
      },
      "taxonomy" : {
        "name" : "ott",
        "version" : "2.9draft12"
      }
    },
    "terminal" : {
      "pg_2822_tree6569" : "ott696271"
    },
    "tip_descendants" : 14302,
    "synth_id" : "opentree4.1"
  },
  "taxon" : {
    "tax_sources" : {
      "irmng" : "1142",
      "worms" : "1836",
      "gbif" : "212",
      "ncbi" : "8782"
    },
    "unique_name" : "Aves",
    "name" : "Aves",
    "rank" : "class",
    "ott_id" : 81461
  },
  "node_id" : "ott81461"
}

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenTreeOfLife/treemachine/issues/206#issuecomment-185025895>
.

**Comment by josephwb** [comment]
i have _no idea_ what you mean by this comment. you like it? i don't really expect that. i am sure there will be discussion regarding the "synth_data" label; please tell me what would be more appropriate. you probably are not happy with the separated keys and source_id_map. please comment on them so i know what you want.

**Comment by jar398** [comment]
The purpose of node_info, and the synth_info details, are off topic and
should be taken up elsewhere

node_id is also off topic but it seems straightforward to me so I'll try
again here. I assume your question is why should the node_id be returned,
if it's provided as a parameter. Suppose you ask for node_info of
mrcaott123ott456, and that node is known to tm-lite canonically as
mrcaott789ott246. That is, they two ids designate the same node, but when
tm-lite returns an id for the node in other contexts (e.g. from mrca), it
will return the latter.  Then the node_id field of the result should
be mrcaott789ott246 (which is not the same as the node_id argument).​

The taxon fields are also a problem for the mrca method, and the whole
story involves nearest_taxon as well. I'll prepare a document that goes
into this and we can do proper reviews.
