### ISSUE TITLE
Trouble spots in v3/tree_of_life API

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#207]
* Support `node_id` in `nearest_taxon` in `/node_info` test
    * [ ] doc
    * [x] test
    * [x] implemented
* `tax_sources` should be strings in `/node_info`, `/mrca`
    * [x] decision
    * [ ] change doc
    * [x] test
    * [ ] implemented
* Add `tax_sources` to taxon blobs?
    * [ ] decision: everywhere (e.g. `/mrca`) or just some places (arguson)
    * [ ] change doc
    * [ ] test
    * [ ] implemented
* `ott_id` is integer everywhere (including arguson)
    * [x] doc
    * [ ] test
    * [ ] implemented
* `rank` (not `tax_rank`) uniformly
    * [ ] doc
    * [ ] test
    * [ ] implemented (I think arguson is the only holdout)
* Include `unique_name` in taxon blob in `/node_info`, `/mrca`, arguson 
    * [ ] decision (all, some, none)
    * [ ] doc
    * [ ] test
    * [ ] implemented
* Include annotations in `/node_info` result always, or controlled by `include_annotations` flag?
    * [ ] decision
    * [ ] doc
    * [ ] test
    * [ ] implemented
* Name of annotations property for `/node_info` result - `annotations` ? or no property at all?
    * [ ] decision
    * [ ] doc
    * [ ] test
    * [ ] implemented
* Format of source list returned by `/about`
    * [ ] separate issue
* Format of `source_id`s everywhere in API: `_` vs. `#` vs. ...
    * [ ] separate issue
* New method / extend existing to replace `v1/getSyntheticTree`
    * [ ] separate issue
* At least one test for each service
    * [ ] `subtree`
    * [ ] `induced_subtree`

I guess we can add to this list by editing the issue description at github.

**Comment by josephwb** [comment]
I don't understand "tax_sources should be strings in /node_info, /mrca".

Does this mean you want:
```
"tax_source" : "ncbi:56337,gbif:2481066,irmng:10591842"
```
instead of:
```
"tax_sources" : {
      "irmng" : "1142",
      "worms" : "1836",
      "gbif" : "212",
      "ncbi" : "8782"
    }
```
Jim asked for the latter; I thought it was for everything (not just arguson). The former version was just lazy, really.

Do you want me to revert it to the single string?

**Comment by jar398** [comment]
It should be as documented in the arguson doc
https://github.com/OpenTreeOfLife/germinator/wiki/%22Arguson%22-format

I'll prepare an API spec that we can talk about and (if no one objects)
work from

**Comment by jar398** [comment]
Given that we are no longer in a crazy deadline crunch, and that this issue has elicited so little interest, I think it makes sense to step back and look at the API as a whole, rather then deal with a bunch of little issues. I plan to draft an informal API spec that we can discuss & work from. I'll submit it as a separate issue when it's ready. This will probably be after the workshops are over; I'll aim for around the 26th.

**Comment by jimallman** [comment]
> Jim asked for the latter; I thought it was for everything (not just arguson).

Sorry for the confusion. At the time, I didn't realize that a taxonomic source could be a bare URL and not part of a recognized taxonomy.

**Comment by jar398** [comment]
This issue is overtaken by https://github.com/OpenTreeOfLife/germinator/issues/48 (although there are a few design questions mentioned above, such as whether to add unique_name everywhere taxon info is returned, that still need to be captured there)
