### ISSUE TITLE
How did treemachine compute total_OTU_count ?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#217]
The statistics file has a comment "total_OTU_count calculated from Processed_newicks/*.tre",

Does anyone ( @josephwb @blackrim ) know how? I'm trying to get a comparable number out of propinquity, and need to know what to ask for. When I do a calculation that I would think is comparable, I get a wildly different number (60000 vs. 40000).

The propinquity issue is here: https://github.com/OpenTreeOfLife/propinquity/issues/15  and has additional background and speculation.

**Comment by josephwb** [comment]
This was calculated using otcetera (not treemachine), and was the number of unique terminal taxa in the input trees. These "terminals" need not be species, and need not have made it into the final synthetic tree.

**Comment by josephwb** [comment]
BTW I am positive we had this discussion before. Perhaps there is a log/issue somewhere. It would likely include the PNAS table. HTH.
