### ISSUE TITLE
Fix the child/parent induced subtree problem

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#225]
as noted here:
https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#induced_subtree

and here:
https://github.com/OpenTreeOfLife/feedback/issues/104

**Comment by josephwb** [comment]
? This is not a problem at all; it is working now.

**Comment by jar398** [comment]
Excellent! I was just copying the issue over from the feedback repo. Will close both issues.

**Comment by josephwb** [comment]
Note that v2 would return the tree of _valid_ ids as well as list which ids are bad. The v3 does not return any tree if _any_ of the ids are bad (it just tells you which ones are bad).

**Comment by jar398** [comment]
Yes of course I know that, I'm the one who made the change. The problem has been under discussion for a while now, but there hasn't been an issue for it, so I just created one: https://github.com/OpenTreeOfLife/treemachine/issues/226

**Comment by josephwb** [comment]
I believe _I_ made the change, but regardless I was just making sure that this was still on the radar.

**Comment by jar398** [comment]
We both made the change; you did it in treemachine, I did it in taxomachine.
