### ISSUE TITLE
Total number of tips or species for each arguson node

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/treemachine#63]
It would be nice if each arguson internal node were annotated *not* with nleaves = number of leaves in the arguson tree but rather the total number of leaves in the synthetic tree below that node.

Looks like this would have to be captured in reconstructSourceTreeHelper, then propagated from the jade tree to the arguson tree on conversion. I don't see any purpose in the current 'nleaves' so that property could probably be removed or recycled for this purpose.

**Comment by josephwb** [comment]
I believe this is fixed with 75e4006fb2716faa4167a2bca9fddc358f1f2bfd.

**Comment by josephwb** [comment]
Might as well clean up the casing inconsistencies here while we're at it. Tomorrow.

**Comment by josephwb** [comment]
https://github.com/OpenTreeOfLife/treemachine/pull/191 covers this.
@jimallman: please close this when you merge.
