### ISSUE TITLE
Does treemachine treat a polytomy in a tree of "high priority" as a hard polytomy?

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/treemachine#79]
Gordon and Ruchi reported (in their TreeOfLife_InformationSupport.docx in the https://drive.google.com/folderview?id=0B3yKYQFpnM_LQWRIY3UzQy01dVk&usp=sharing synthesis_paper folder) what appear to be cases in which synthetic tree returns a polytomy, but there are groupings in a source tree that could resolve them: 

"Most input trees have very low ATE values with respect to the tree of life, but some have extremely high ATE values. 147 of the 335 input trees have an ATE of 0 with respect to the pruned tree of life.  However, 26 input trees have an ATE of 100, and 44 have an ATE ≥ 90.  In almost all of the trees with extremely high ATE values, the tree of life has few if any internal nodes matching the leaf sets of the input tree.  In other words, the input tree may be very resolved for that set of taxa, but the tree of life is nearly or completely unresolved"

Is this an indication that polytomies in a high priority trees are treated as "hard polytomies" ? If so, can/should we change that?

**Comment by josephwb** [comment]
Deprecated.
